#!/usr/bin/env bash
# Set the name of the private key
KEY_NAME="school"
# Set the number of bits for the key
KEY_BITS=4096
# Set the passphrase for the key
KEY_PASSPHRASE="betty"
# Generate the key pair
ssh-keygen -t rsa -b $KEY_BITS -f ~/.ssh/$KEY_NAME -N $KEY_PASSPHRASE
# Output the public key for easy copy-pasting
echo "Here is the public key:"
