#!/usr/bin/env bash 
# installing Nginx and performing actions
apt-get update -y
apt-get install nginx -y
ERRDIR="\\\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}\n"
HEADER="\\\n\tadd_header X-Served-By \$HOSTNAME;\n"
SRC="/etc/nginx/sites-available/default"
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
     location /redirect_me {
        return 301 https://www.youtube.com/watch?v=mC-zw0zCCtg;
    }
}
" > /etc/nginx/sites-available/default
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "40i $ERRDIR" $SRC
sudo sed -i "28i $HEADER" $SRC
# Restart nginx
sudo service nginx restart

