#!/usr/bin/env bash
#setting up load balancing
sudo apt update -y
sudo apt install haproxy -y
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'listen 5515-webs
        server 5515-web-01 54.160.162.167:80 check
        server 5515-web-02 54.165.86.206:80 check
        bind *:80
        mode http
        balance roundrobin
' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
