#!/usr/bin/env bash 
# installing Nginx and performing actions
sudo apt-get update
sudo apt-get install nginx -y
# Configure Nginx
echo "Holberton School" > /etc/nginx/sites-available/default
# Restart Nginx 
sudo service nginx restart
