#!/usr/bin/env bash 
# installing Nginx and performing actions
apt-get update -y
apt-get install nginx -y
# Configure Nginx
echo "Holberton School" | sudo tee /etc/nginx/sites-available/default
# Restart Nginx 
sudo service nginx restart
