#!/usr/bin/env bash 
# installing Nginx and performing actions
apt-get update -y
apt-get install nginx -y
REDIR="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=mC-zw0zCCtg;\n\t}\n"
SRC="etc/nginx/sites-available/default"
sudo sed -i "30i $REDIR" $SRC
service nginx restart
