#!/usr/bin/env bash 
# installing Nginx and performing actions
apt-get update -y
apt-get install nginx -y
# Configure Nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
# setting the redirection
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm index.nginx-debian.html;
     location /redirect_me {
        return 301 https://www.youtube.com/watch?v=mC-zw0zCCtg;
    }
}
" > /etc/nginx/sites-available/default
# Restart nginx
sudo service nginx restart
