#!/usr/bin/env bash
# 404
apt-get update
apt-get -y install nginx
# create a custom 404 HTML file
sudo vi /usr/share/nginx/html/custom_404.html
# Configure Nginx to use custom 404 page
sudo vi /etc/nginx/nginx.conf
# Test Nginx configuration
sudo nginx -t
# Reload/Restart  Nginx
service nginx restart
