#!/usr/bin/env bash
# 404
apt-get update
apt-get -y install nginx
# Create custom 404 error page
echo "<!DOCTYPE html>
<html>
<head>
  <title>404 Not Found</title>
</head>
<body>
  <h1>404/h1>
  <p>Ceci n'est pas une page</p>
</body>
</html>" | sudo tee /var/www/html/custom_404.html >/dev/null
sudo service nginx restart
